version: 0.0
os: linux
files:
  - source: /Gemfile
    destination: /home/ubuntu/app-rails
  - source: /Gemfile.lock
    destination: /home/ubuntu/app-rails
#  - source: /Rakefile
#    destination: /home/ubuntu/app-rails
#  - source: /README.md
#    destination: /home/ubuntu/app-rails
  - source: /app/
    destination: /home/ubuntu/app-rails/app
#  - source: /config/
#    destination: /home/ubuntu/app-rails/config
  - source: /lib/
    destination: /home/ubuntu/app-rails/lib
  - source: /log/
    destination: /home/ubuntu/app-rails/log
  - source: /vendor/
    destination: /home/ubuntu/app-rails/vendor
  - source: /public/
    destination: /home/ubuntu/app-rails/public
hooks:
  AfterInstall:
    - location: scripts/dependencies_install.sh
      runas: ubuntu