version: 0.0
os: linux
destination: app-rails
permissions:
  - object: app-rails
pattern: "**"
owner: ubuntu
group: ubuntu
mode: 775
hooks:
  AfterInstall:
    - location: scripts/dependencies_install.sh
      runas: ubuntu
  ApplicationStart:
    - location: scripts/application_start.sh
      runas: ubuntu