version: 0.0
os: linux
destination: /var/www/app-rails/
permissions:
  - object: /var/www/app-rails/
pattern: “**”
owner: ubuntu
group: ubuntu
mode: 775
hooks:
  AfterInstall:
    - location: scripts/dependencies_install.sh
      runas: ubuntu